#!/usr/bin/env python
"""Reference lifecycle smoke for the exported agent-loop core (Slice 5).

Everything in this smoke is synthetic reference evidence: every identity,
decision, and artifact is locally generated by this script. It is never a
real owner decision and never an actual third-party review, and no actor
label here is an authenticated identity claim.

Run it isolated from an unrelated fixture project:

    python -I -S -B smoke.py

It uses only the Python standard library and the copied
``agent_loop_contract.py`` sitting next to this file. Verify before use:
the smoke first verifies the complete known member inventory and the byte
identity of every copied member against the frozen export manifest, and
only then imports the copied core, so a corrupted or incomplete copy fails
closed without executing any copied module. It then demonstrates the full
loop:

    candidate -> intent preflight -> validation -> frozen envelope ->
    two-pass evidence, durable correction and review convergence ->
    review passed -> explicit manual owner decision

through a provider-neutral, manual-by-default reference acceptance gate,
and proves the failing cases: tampered member bytes, tampered proof bytes,
missing required evidence, equal comparable fingerprint conflicts,
implementer self-acceptance, review-only-as-acceptance, absent or
non-accepting explicit decisions, implementer/reviewer actors with an
otherwise valid reviewed candidate, candidate byte or proof drift on the
acceptance path, conflicting complete fingerprints, an understated or
materially ambiguous intent preflight, and an unconverged accepting review
are all refused.
The accepted core's optional engineer-route selection API stays inert: the
portable reference never calls it and never selects a provider.

Exit code 0 means every positive and negative expectation held; any other
exit code is a fail-closed result with a printed reason.
"""
from __future__ import annotations

import hashlib
import json
import sys
import tempfile
from pathlib import Path

MANIFEST_SCHEMA = "agent-loop-core-export-manifest/1"
SYNTHETIC_TASK = "synthetic-agent-loop-smoke"
SYNTHETIC_COMMAND = "python -I -S -B smoke.py"
# The frozen synthetic requirement ids of the reference intent preflight.
SYNTHETIC_REQUIREMENT_IDS = ("R1", "R2")

# The complete known member inventory of this export: sorted exact
# coverage is verified from the manifest before any copied module loads.
REQUIRED_MEMBERS = (
    "README.md",
    "EXPORT_AUDIT.md",
    "REVIEW.md",
    "TASK.md",
    "agent_loop_contract.py",
    "smoke.py",
)

# Synthetic local actor label for the reference decision. It is a fixture
# label inside one local run, never an authenticated identity claim.
OWNER_ACTOR = "OWNER"


class SmokeFailure(Exception):
    """A fail-closed integrity violation in the copied export."""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _member_digest(items) -> str:
    """The documented runner oracle: SHA-256 over each member in fence
    order as ``member\\0<sha256-of-stored-bytes>\\n``."""
    hasher = hashlib.sha256()
    for name, data in items:
        hasher.update(name.encode("utf-8"))
        hasher.update(b"\0")
        hasher.update(_sha256(data).encode("ascii"))
        hasher.update(b"\n")
    return hasher.hexdigest()


def verify_own_bytes(base: Path) -> None:
    """Verify-before-use: the complete known member inventory (sorted,
    unique, exact coverage) and the byte identity of every copied member
    are checked BEFORE any copied module is imported. Unknown, missing,
    duplicate, unsorted, or incomplete manifests fail closed, so a
    corrupted copy can never execute."""
    manifest_path = base / "manifest.json"
    if not manifest_path.is_file():
        raise SmokeFailure("MANIFEST_MISSING")
    try:
        manifest = json.loads(manifest_path.read_bytes().decode("utf-8"))
    except (OSError, UnicodeDecodeError, ValueError):
        raise SmokeFailure("MANIFEST_UNREADABLE") from None
    if (not isinstance(manifest, dict)
            or manifest.get("schema") != MANIFEST_SCHEMA):
        raise SmokeFailure("MANIFEST_UNKNOWN_SCHEMA")
    members = manifest.get("members")
    if not isinstance(members, list) or not members:
        raise SmokeFailure("MANIFEST_MALFORMED")
    names: list = []
    previous = None
    for entry in members:
        if not isinstance(entry, dict):
            raise SmokeFailure("MANIFEST_MALFORMED")
        rel = entry.get("path")
        if (not isinstance(rel, str) or not rel or rel in (".", "..")
                or "/" in rel or "\\" in rel):
            raise SmokeFailure("MANIFEST_MALFORMED")
        if rel in names:
            raise SmokeFailure(f"MANIFEST_DUPLICATE_MEMBER:{rel}")
        if previous is not None and rel < previous:
            raise SmokeFailure("MANIFEST_MEMBERS_UNSORTED")
        names.append(rel)
        previous = rel
    if names != sorted(REQUIRED_MEMBERS):
        raise SmokeFailure("MANIFEST_INCOMPLETE_INVENTORY")
    for entry in members:
        rel = entry["path"]
        try:
            data = (base / rel).read_bytes()
        except OSError:
            raise SmokeFailure(f"MEMBER_MISSING:{rel}") from None
        if (len(data) != entry.get("bytes")
                or _sha256(data) != entry.get("sha256")):
            raise SmokeFailure(f"MEMBER_IDENTITY_MISMATCH:{rel}")


def _proof_line(artifact: str, sha: str, origin: str, action: str) -> str:
    return ("`validation-review-proof/1` artifact `" + artifact
            + "` sha256 `" + sha + "` origin `" + origin
            + "` action `" + action + "` candidate `" + SYNTHETIC_TASK + "`")


def _review_text(sha_one: str, sha_two: str) -> str:
    requirement_ids = ",".join(SYNTHETIC_REQUIREMENT_IDS)
    return (
        "# Architect Review — " + SYNTHETIC_TASK
        + " (synthetic reference)\n\n"
        "## Contract compliance\n\n"
        "- Verdict: `PASS`\n"
        "- Evidence: " + _proof_line(
            "proof_contract_compliance.json", sha_one,
            "REVIEWER_RECOMPUTED",
            "recomputed the synthetic frozen envelope digests") + "\n\n"
        "## Adversarial validity\n\n"
        "- Verdict: `PASS`\n"
        "- Evidence: " + _proof_line(
            "proof_adversarial_validity.json", sha_two,
            "REVIEWER_REEXECUTED",
            "re-executed the synthetic reference lifecycle checks") + "\n\n"
        "## Findings\n\n"
        "## Durable correction\n\n"
        "- Mandated change: `NONE`\n"
        "\n## Convergence disposition\n\n"
        "- Disposition: `CONVERGED`\n"
        "- Covered requirement IDs: `" + requirement_ids + "`\n"
        "- Remaining material requirement IDs: `NONE`\n"
    )


def synthetic_task_preflight_text() -> str:
    """A synthetic provider-neutral task contract with a FULL intent
    preflight: exact coverage over the frozen synthetic requirement ids,
    one numbered success criterion and one fenced validation command each."""
    requirement_ids = ",".join(SYNTHETIC_REQUIREMENT_IDS)
    return (
        "# ACTIVE_TASK — synthetic reference\n\n"
        "## Intent preflight\n\n"
        "- Mode: `FULL`\n"
        "- Clarification status: `RESOLVED`\n"
        "- Open material clarification IDs: `NONE`\n"
        "- Assumption IDs: `NONE`\n"
        "- Requirement IDs: `" + requirement_ids + "`\n"
        "\n### Requirement coverage\n\n"
        "| Requirement | Success criterion | Validation command "
        "| Planned evidence |\n"
        "|---|---:|---:|---|\n"
        "| R1 | 1 | 1 | `TEST_OUTPUT` |\n"
        "| R2 | 2 | 1 | `TEST_OUTPUT` |\n"
        "\n## Success criteria\n\n"
        "1. First synthetic criterion.\n"
        "2. Second synthetic criterion.\n"
        "\n## Validation command budget\n\n"
        "Only these exact focused commands may run:\n\n"
        "```text\n" + SYNTHETIC_COMMAND + "\n```\n"
    )


def _synthetic_facts(contract, *, risk: str = "LOW") -> dict:
    """Hand-declared work facts for the preflight mode derivation."""
    return {"decision": contract.ROUTING_FACTS_PRESENT,
            "work_kind": "IMPLEMENTATION", "risk": risk,
            "oracle_strength": "STRONG", "novelty": "ROUTINE",
            "ambiguity": "CLEAR", "failure_evidence": "NONE",
            "escalation_evidence": "NONE", "clerical_package": "OTHER",
            "authority_domains": [], "material_contradiction": False}


def build_reference_evidence(tmp: Path, contract) -> dict:
    """Write the shared synthetic reference seam: the candidate members,
    one counted validation occurrence, the frozen envelope, and the
    two-pass review artifacts. Returns every piece the reference
    acceptance gate re-checks. Synthetic reference evidence only."""
    members = (
        ("alpha.py", b"VALUE = 1\n"),
        ("beta.md", "отчёт ✓\n".encode("utf-8")),
    )
    for name, data in members:
        (tmp / name).write_bytes(data)
    candidate_sha = _member_digest(members)

    # One counted synthetic validation occurrence, fully fingerprinted.
    fingerprint = contract.build_occurrence_fingerprint(
        candidate_digest=candidate_sha,
        command_argv=SYNTHETIC_COMMAND,
        environment_policy_identity="synthetic-clean-fixture-allowlist",
        platform_identity=contract.platform_identity(),
        declared_seed="0")
    evidence_state = contract.classify_validation_evidence(
        occurrence_count=1, invalid_captures=0,
        nondeterministic_conflicts=0, unproven_captures=0)

    # Frozen envelope: member bytes and digests written once.
    envelope = {
        "schema": "synthetic-reference-envelope/1",
        "task": SYNTHETIC_TASK,
        "candidate_sha256": candidate_sha,
        "members": [
            {"path": name, "bytes": len(data), "sha256": _sha256(data)}
            for name, data in members
        ],
        "validation": {"evidence_state": evidence_state,
                       "fingerprint": dict(fingerprint)},
    }
    (tmp / "envelope.json").write_bytes(
        json.dumps(envelope, ensure_ascii=True, sort_keys=True,
                   indent=2).encode("utf-8") + b"\n")

    # Two-pass review with proof-backed evidence and a durable-correction
    # block over zero findings (nothing is invented).
    proof_one = tmp / "proof_contract_compliance.json"
    proof_two = tmp / "proof_adversarial_validity.json"
    proof_one.write_bytes(json.dumps(
        {"task": SYNTHETIC_TASK, "pass": "Contract compliance"},
        sort_keys=True).encode("utf-8") + b"\n")
    proof_two.write_bytes(json.dumps(
        {"task": SYNTHETIC_TASK, "pass": "Adversarial validity"},
        sort_keys=True).encode("utf-8") + b"\n")
    review_text = _review_text(_sha256(proof_one.read_bytes()),
                               _sha256(proof_two.read_bytes()))
    return {
        "members": members,
        "candidate_sha256": candidate_sha,
        "fingerprint": dict(fingerprint),
        "envelope": envelope,
        "review_text": review_text,
        "proof_one": proof_one,
        "proof_two": proof_two,
        "requirement_ids": list(SYNTHETIC_REQUIREMENT_IDS),
    }


def synthetic_owner_decision(candidate_sha: str) -> dict:
    """A synthetic explicit manual owner acceptance decision bound to one
    reviewed candidate. Local reference evidence only: the owner actor is
    a fixture label, never an authenticated identity claim."""
    return {
        "schema": "agent-loop-acceptance-record/1",
        "task": SYNTHETIC_TASK,
        "actor": OWNER_ACTOR,
        "decision": "ACCEPTED",
        "candidate_sha256": candidate_sha,
    }


def reference_manual_acceptance(contract, tmp: Path, evidence: dict,
                                decision, *, rerun_outcome=0) -> list:
    """The portable reference acceptance gate over synthetic evidence.

    Returns fail-closed refusal reasons; an empty list accepts. A passed
    review is never acceptance: this gate re-verifies the review
    artifacts, the frozen candidate bytes, and the validation evidence at
    acceptance time, then requires an explicit manual owner decision bound
    to this exact reviewed candidate. Every actor and decision here is a
    synthetic local assertion, never an authenticated identity claim; no
    engineer route or provider selection is consulted.
    """
    refusals: list = []
    envelope = evidence["envelope"]

    # The review gate is re-checked over the stored artifacts: tampered
    # proof bytes refuse this same acceptance path. A FULL-task accepting
    # review is additionally convergence-bound to the frozen requirement
    # ids: a missing or unconverged disposition refuses the same path.
    for error in contract.parse_two_pass_review(
            evidence["review_text"], root=tmp, task_id=SYNTHETIC_TASK):
        refusals.append("ACCEPTANCE_REFUSED_REVIEW_GATE:" + error)
    for error in contract.validate_correction_dispositions(
            evidence["review_text"], root=tmp):
        refusals.append("ACCEPTANCE_REFUSED_REVIEW_GATE:" + error)
    for error in contract.validate_convergence_disposition(
            evidence["review_text"],
            evidence.get("requirement_ids") or [], accepting=True):
        refusals.append("ACCEPTANCE_REFUSED_REVIEW_GATE:" + error)

    # Candidate bytes must still match the frozen envelope member digests:
    # candidate drift refuses this same acceptance path.
    for member in envelope["members"]:
        try:
            data = (tmp / member["path"]).read_bytes()
        except OSError:
            refusals.append(
                "ACCEPTANCE_REFUSED_CANDIDATE_DRIFT:" + member["path"])
            continue
        if (len(data) != member["bytes"]
                or _sha256(data) != member["sha256"]):
            refusals.append(
                "ACCEPTANCE_REFUSED_CANDIDATE_DRIFT:" + member["path"])

    # Validation evidence must be verified, and an equal complete
    # fingerprint with a conflicting rerun outcome is nondeterminism that
    # blocks the acceptance path.
    if envelope["validation"]["evidence_state"] != "VERIFIED":
        refusals.append("ACCEPTANCE_REFUSED_EVIDENCE_NOT_VERIFIED")
    classification = contract.classify_fingerprint_pair(
        evidence["fingerprint"], 0, evidence["fingerprint"], rerun_outcome)
    if classification != contract.CONSISTENT:
        refusals.append("ACCEPTANCE_REFUSED_FINGERPRINT_" + classification)

    # The explicit manual decision: present, owner-made, accepting, and
    # bound to this exact reviewed candidate.
    if decision is None:
        refusals.append("ACCEPTANCE_REFUSED_NO_EXPLICIT_DECISION")
    else:
        if decision.get("actor") != OWNER_ACTOR:
            refusals.append(
                "ACCEPTANCE_REFUSED_DECISION_ACTOR:"
                + str(decision.get("actor")))
        if decision.get("decision") != "ACCEPTED":
            refusals.append("ACCEPTANCE_REFUSED_DECISION_NOT_ACCEPTED")
        if decision.get("candidate_sha256") != envelope["candidate_sha256"]:
            refusals.append("ACCEPTANCE_REFUSED_DECISION_UNBOUND")
    return refusals


def run_reference_flow(tmp: Path, contract, failures: list) -> None:
    """Positive loop and negative cases over synthetic reference evidence."""

    def expect(condition: bool, case: str) -> None:
        if not condition:
            failures.append("EXPECTATION_FAILED:" + case)

    def expect_detected(detected: bool, case: str) -> None:
        if not detected:
            failures.append("NEGATIVE_CASE_NOT_DETECTED:" + case)

    evidence = build_reference_evidence(tmp, contract)
    members = evidence["members"]
    envelope = evidence["envelope"]
    proof_two = evidence["proof_two"]

    expect(contract.fingerprint_is_complete(evidence["fingerprint"]),
           "fingerprint_complete")
    expect(contract.CONSISTENT == contract.classify_fingerprint_pair(
        evidence["fingerprint"], 0, dict(evidence["fingerprint"]), 0),
        "consistent_rerun")
    expect("VERIFIED" == contract.classify_validation_evidence(
        occurrence_count=1, invalid_captures=0,
        nondeterministic_conflicts=0, unproven_captures=0),
        "evidence_verified")

    expect(contract.parse_two_pass_review(
        evidence["review_text"], root=tmp,
        task_id=SYNTHETIC_TASK) == [],
        "two_pass_review_proven")
    expect(contract.validate_correction_dispositions(evidence["review_text"],
                                                     root=tmp) == [],
        "durable_correction_valid")

    # Intent preflight (provider-neutral): the synthetic FULL task validates
    # against the low-risk-class facts; an understated LIGHT declaration and
    # material ambiguity are refused before any paid writer could exist.
    preflight_text = synthetic_task_preflight_text()
    lights = _synthetic_facts(contract)
    expect(contract.validate_intent_preflight(
        preflight_text, required=True, facts=lights,
        restricted_authority=False) == [],
        "intent_preflight_full_valid")
    expect_detected(bool(contract.validate_intent_preflight(
        preflight_text.replace("- Mode: `FULL`", "- Mode: `LIGHT`"),
        required=True, facts=_synthetic_facts(contract, risk="HIGH"))),
        "understated_preflight_refused")
    blocked = contract.parse_intent_preflight(preflight_text.replace(
        "- Clarification status: `RESOLVED`",
        "- Clarification status: `BLOCKED`"))
    expect_detected(bool(contract.intent_preflight_material_ambiguity(
        blocked, lights)), "material_ambiguity_refused")

    # Review convergence: the accepting review is exact over the frozen
    # requirement ids; a material-delta verdict and a missing disposition
    # refuse the accepting path of the SAME valid reviewed candidate.
    requirement_ids = list(SYNTHETIC_REQUIREMENT_IDS)
    expect(contract.validate_convergence_disposition(
        evidence["review_text"], requirement_ids,
        accepting=True) == [],
        "convergence_exact")
    expect_detected(bool(contract.validate_convergence_disposition(
        evidence["review_text"].replace(
            "- Disposition: `CONVERGED`", "- Disposition: `MATERIAL_DELTA`"
        ).replace("- Remaining material requirement IDs: `NONE`",
                  "- Remaining material requirement IDs: `R2`"),
        requirement_ids, accepting=True)),
        "material_delta_cannot_accept")
    expect_detected(bool(contract.validate_convergence_disposition(
        evidence["review_text"].replace(
            "## Convergence disposition", "## Convergence record"),
        requirement_ids, accepting=True)),
        "missing_convergence_refused")

    # Lifecycle: a passed review is never acceptance; only the explicit
    # manual owner decision accepts (the decision below is a synthetic
    # reference decision, not a real one).
    expect(contract.validate_task_transition(
        "ACTIVE", "PENDING_CODEX_REVIEW") == [],
        "transition_to_review")
    expect(contract.validate_task_transition(
        "PENDING_CODEX_REVIEW", "REVIEW_PASSED") == [],
        "transition_review_passed")
    expect(contract.validate_task_transition(
        "REVIEW_PASSED", "ACCEPTED") == [],
        "transition_manual_acceptance")
    expect(contract.validate_task_transition(
        "ACCEPTED", "RELEASED") == [],
        "transition_released")

    # The reference acceptance gate: a valid reviewed candidate accepts
    # only through an explicit manual owner decision bound to it.
    owner_decision = synthetic_owner_decision(evidence["candidate_sha256"])
    expect(reference_manual_acceptance(
        contract, tmp, evidence, owner_decision) == [],
        "explicit_owner_decision_accepts")

    # Negative cases: absent, non-owner, and non-accepting explicit
    # decisions refuse the acceptance path of the SAME valid reviewed
    # candidate.
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence, None), "absent_decision_refused")
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence,
        dict(owner_decision, actor="IMPLEMENTER")),
        "implementer_decision_refused")
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence,
        dict(owner_decision, actor="REVIEWER")),
        "reviewer_decision_refused")
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence,
        dict(owner_decision, decision="REJECTED")),
        "non_accepting_decision_refused")

    # Negative cases: candidate byte drift and proof byte drift refuse the
    # same acceptance path; the original bytes are restored afterwards.
    name, original = members[0]
    (tmp / name).write_bytes(original + b"# tampered\n")
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence, owner_decision), "candidate_drift_refused")
    (tmp / name).write_bytes(original)
    proof_original = proof_two.read_bytes()
    proof_two.write_bytes(proof_original + b"# tampered\n")
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence, owner_decision), "proof_drift_refused")
    proof_two.write_bytes(proof_original)

    # Negative case: conflicting complete fingerprints block acceptance.
    expect_detected(reference_manual_acceptance(
        contract, tmp, evidence, owner_decision, rerun_outcome=1),
        "conflicting_fingerprints_block")

    # Negative case: tampered member bytes no longer match the frozen
    # envelope digest.
    tampered = members[0][1] + b"# tampered\n"
    expect_detected(_sha256(tampered) != envelope["members"][0]["sha256"],
                    "tampered_member_bytes")

    # Negative case: tampered proof bytes fail the proof-record hash check.
    proof_two.write_bytes(proof_original + b"# tampered\n")
    errors = contract.parse_two_pass_review(evidence["review_text"],
                                            root=tmp,
                                            task_id=SYNTHETIC_TASK)
    expect_detected(any("HASH_MISMATCH" in error for error in errors),
                    "tampered_proof_bytes")
    proof_two.write_bytes(proof_original)

    # Negative case: a missing required evidence line fails closed.
    missing_evidence_review = (
        "# Architect Review — " + SYNTHETIC_TASK + "\n\n"
        "## Contract compliance\n\n"
        "- Verdict: `PASS`\n\n"
        "## Adversarial validity\n\n"
        "- Verdict: `PASS`\n"
        "- Evidence: " + _proof_line(
            "proof_adversarial_validity.json", "f" * 64,
            "REVIEWER_REEXECUTED", "recorded action") + "\n\n"
        "## Findings\n\n"
        "## Durable correction\n\n"
        "- Mandated change: `NONE`\n"
    )
    errors = contract.parse_two_pass_review(missing_evidence_review)
    expect_detected(any("EVIDENCE_EMPTY" in error for error in errors),
                    "missing_required_evidence")

    # Negative case: equal complete fingerprints with conflicting outcomes
    # are nondeterminism, never a lucky rerun.
    expect_detected(
        contract.NONDETERMINISTIC == contract.classify_fingerprint_pair(
            evidence["fingerprint"], 0, dict(evidence["fingerprint"]), 1),
        "equal_fingerprint_conflict")

    # Negative case: implementer self-acceptance without a valid two-pass
    # review artifact is refused.
    self_claimed_review = (
        "# Implementer claim\n\n"
        "- Verdict: `PASS`\n"
        "- Claimed by the implementer without independent proof.\n")
    errors = contract.parse_two_pass_review(self_claimed_review)
    expect_detected(bool(errors), "implementer_acceptance_refused")

    # Negative case: review-only-as-acceptance — a passed review can never
    # reach the released state without the explicit acceptance state.
    errors = contract.validate_task_transition("REVIEW_PASSED", "RELEASED")
    expect_detected(bool(errors), "review_only_not_acceptance")


def main() -> int:
    base = Path(__file__).resolve().parent
    # Verify before use: the complete known inventory and byte identities
    # are verified BEFORE any copied module is imported, so a corrupted or
    # incomplete copy can never execute.
    try:
        verify_own_bytes(base)
    except SmokeFailure as exc:
        print("AGENT_LOOP_SMOKE: FAIL " + str(exc))
        return 2
    if str(base) not in sys.path:
        sys.path.insert(0, str(base))
    try:
        import agent_loop_contract as contract
    except ModuleNotFoundError:
        print("AGENT_LOOP_SMOKE: FAIL CORE_MEMBER_UNIMPORTABLE")
        return 2
    failures: list = []
    try:
        with tempfile.TemporaryDirectory(dir=str(base)) as tmp_name:
            run_reference_flow(Path(tmp_name), contract, failures)
    except Exception as exc:  # unexpected behavior fails closed, never passes
        print("AGENT_LOOP_SMOKE: FAIL UNEXPECTED "
              + type(exc).__name__ + ": " + str(exc))
        return 3
    if failures:
        print("AGENT_LOOP_SMOKE: FAIL " + "; ".join(failures))
        return 1
    print("AGENT_LOOP_SMOKE: PASS (synthetic reference evidence only; "
          "no real owner decision or third-party review occurred)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
